name: wdurden
favicon: null
layout_spectrum: 0.37851488310843706
typography_spectrum: 0.7894504754804075
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7789053516462445
  lightness: 0.7868241681717336
  saturation: 0.5691219998989254
  rhythmicContrast: 0.21667590457946062
purpose: []
